image: docker:latest

services:
  - docker:dind

stages:
  - unit_test
  - build_tag
  - build_latest
  - push_registry

unit_test:
  stage: unit_test
  image: golang:1.13-alpine
  before_script:
    - apk add --no-cache curl git openssh-client build-base
  script:
    - mkdir -p /root/.ssh && chmod 0700 /root/.ssh
    - echo "$SSH_PUBLIC_KEY" > /root/.ssh/id_rsa.pub
    - chmod 600 /root/.ssh/id_rsa.pub
    - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - ssh-keyscan gitlab.com > /root/.ssh/known_hosts
    - cat /root/.ssh/id_rsa.pub
    - cat /root/.ssh/id_rsa
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - export GO111MODULE=on
    - go get -u golang.org/x/lint/golint
    - go mod download
    - make test
    # will be fix in next issue
    # - golint -set_exit_status $(go list ./...)
  only:
    - branches

build_vanilla:
  stage: build_tag
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --build-arg ssh_prv_key="$SSH_PRIVATE_KEY" --build-arg ssh_pub_key="$SSH_PUBLIC_KEY" --network host .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags

push_docker_hub:
  stage: push_registry
  rules:
    - if: '$CI_COMMIT_TAG =~ /^([0-9]+)\.([0-9]+)\.([0-9]+)$/'
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker login --username nodefluxio --password ${DOCKERHUB_ACCESS_TOKEN}
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "nodefluxio/vanilla-dashboard:$CI_COMMIT_TAG"
    - docker push "nodefluxio/vanilla-dashboard:$CI_COMMIT_TAG"

build_plugin_search:
  stage: build_tag
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -f Dockerfile.plugin -t "registry.gitlab.com/nodefluxio/vanilla-dashboard/search:$CI_COMMIT_TAG" --build-arg ssh_prv_key="$SSH_PRIVATE_KEY" --build-arg ssh_pub_key="$SSH_PUBLIC_KEY" --network host .
    - docker push "registry.gitlab.com/nodefluxio/vanilla-dashboard/search:$CI_COMMIT_TAG"
  only:
    - tags

build_latest:
  stage: build_latest
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:latest" --build-arg ssh_prv_key="$SSH_PRIVATE_KEY" --build-arg ssh_pub_key="$SSH_PUBLIC_KEY" --network host .
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker login --username nodefluxio --password ${DOCKERHUB_ACCESS_TOKEN}
    - docker tag "$CI_REGISTRY_IMAGE:latest" "nodefluxio/vanilla-dashboard:latest"
    - docker push "nodefluxio/vanilla-dashboard:latest"
  only:
    - master
