// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "gitlab.com/nodefluxio/vanilla-dashboard/internal/entity"
)

// Coordinator is an autogenerated mock type for the Coordinator type
type Coordinator struct {
	mock.Mock
}

// GetEnrollmentEvent provides a mock function with given fields: ctx, limit, lastestTimestamp
func (_m *Coordinator) GetEnrollmentEvent(ctx context.Context, limit int, lastestTimestamp string) (*entity.EnrollmentEventCoordinator, error) {
	ret := _m.Called(ctx, limit, lastestTimestamp)

	var r0 *entity.EnrollmentEventCoordinator
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *entity.EnrollmentEventCoordinator); ok {
		r0 = rf(ctx, limit, lastestTimestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EnrollmentEventCoordinator)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, limit, lastestTimestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
