const envVar =
  // eslint-disable-next-line no-underscore-dangle
  process.env.NODE_ENV === "production" ? window._env_ : process.env;
const {
  NODE_ENV,
  REACT_APP_HOST,
  REACT_APP_VISIONAIRE_HOST,
  REACT_APP_LOCAL_PORT,
  REACT_APP_API_CAMERA,
  REACT_APP_API_ENROLLMENT,
  REACT_APP_API_EVENT,
  REACT_APP_API_WEB_SOCKET,
  REACT_APP_API_AUTH,
  PLUGIN_HOST,
  PLUGIN_NAME,
  REACT_APP_REFRESH_TIME,
  REACT_APP_MAX_SIZE_IMG_ENROLLMENT,
  USE_CES,
  LONG_POLL_INTERVAL
} = envVar;

const config = {
  NODE_ENV,
  PUBLIC_URL: process.env.PUBLIC_URL,
  REACT_APP_HOST, // server IP where this repo hosted
  REACT_APP_LOCAL_PORT: REACT_APP_LOCAL_PORT || "4004", // server PORT where this repo hosted
  LOCAL_REACT_PORT: "4019",
  REACT_APP_API_CAMERA:
    REACT_APP_API_CAMERA || `http://${REACT_APP_VISIONAIRE_HOST}`,
  REACT_APP_API_ENROLLMENT:
    REACT_APP_API_ENROLLMENT || `http://${REACT_APP_HOST}/api`,
  REACT_APP_API_AUTH: REACT_APP_API_AUTH || `http://${REACT_APP_HOST}/api`,
  REACT_APP_API_EVENT: REACT_APP_API_EVENT || `http://${REACT_APP_HOST}/api`,
  REACT_APP_API_WEB_SOCKET:
    REACT_APP_API_WEB_SOCKET || `ws://${REACT_APP_HOST}/api`,
  PLUGIN_HOST,
  PLUGIN_NAME,
  REACT_APP_REFRESH_TIME: REACT_APP_REFRESH_TIME || "900000",
  REACT_APP_MAX_SIZE_IMG_ENROLLMENT:
    REACT_APP_MAX_SIZE_IMG_ENROLLMENT || 25000000, // 25MB
  USE_CES: USE_CES || false,
  LONG_POLL_INTERVAL: LONG_POLL_INTERVAL || 3000 // 3s
};

module.exports = config;
