const actionTypes = {
  GET_EVENT_HISTORY_LIST: "GET_EVENT_HISTORY_LIST",
  SHOW_GENERAL_NOTIFICATION: "SHOW_GENERAL_NOTIFICATION",
  CLOSE_GENERAL_NOTIFICATION: "CLOSE_GENERAL_NOTIFICATION",
  USER_LOGIN: "USER_LOGIN",
  USER_UPDATE_DATA: "USER_UPDATE_DATA",
  USER_LOGOUT: "USER_LOGOUT",
  USER_FAILED_AUTH: "USER_FAILED_AUTH",
  USER_RESET_AUTH_ERROR: "USER_RESET_AUTH_ERROR",
  REFRESH_ACCESS_TOKEN: "REFRESH_ACCESS_TOKEN",
  AGENT_STATUS: "AGENT_STATUS",
  CREATE_EXPORT: "CREATE_EXPORT",
  EXPORT_STATUS: "EXPORT_STATUS",
  RESET_DOWNLOADER_STATE: "RESET_DOWNLOADER_STATE"
};

export const {
  GET_EVENT_HISTORY_LIST,
  SHOW_GENERAL_NOTIFICATION,
  CLOSE_GENERAL_NOTIFICATION,
  USER_LOGIN,
  USER_UPDATE_DATA,
  USER_LOGOUT,
  USER_FAILED_AUTH,
  USER_RESET_AUTH_ERROR,
  REFRESH_ACCESS_TOKEN,
  AGENT_STATUS,
  CREATE_EXPORT,
  EXPORT_STATUS,
  RESET_DOWNLOADER_STATE
} = actionTypes;
